# Default config
tabWidth: 4
endOfLine: crlf
singleQuote: true
printWidth: 100000
trailingComma: none
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

# Overrided config
overrides:
  - files: ["*.md", "*.json"]
    options:
      tabWidth: 2
  - files: ["*.css"]
    options:
      singleQuote: false