tabWidth: 4
endOfLine: crlf
singleQuote: true
printWidth: 100000
trailingComma: none
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

overrides:
  - files: ["*.md", "*.json", "*.yaml", "*.css", "*.config.*"]
    options:
      tabWidth: 2
      singleQuote: false
